### PR TITLE
Updated the prerequisites section

### PR DESCRIPTION
**Pull request by shiruba**
First things first, when working on a new project: Improve documentation :-)

I wasn't able to build the project via `pipenv` until I installed libmagic and MySQL.

### CODE REVIEW

**Comment by lifenautjoe** [comment]
Hi @shiruba, thanks and sorry about this. We've had our hands full since launch 😅.

**Comment by lifenautjoe** [comment]
Could you change the target branch to `develop` ?

**Comment by lifenautjoe** [comment]
Oh wait, nevermind, I did it myself :-)

**Comment by shiruba** [comment]
> Hi @shiruba, thanks and sorry about this. We've had our hands full since launch 😅.

No worries :-)

While I am at it, are you interested in a setup guide on macOS using Homebrew? Could contribute that to OpenbookOrg/openbook-app, too.

**Comment by lifenautjoe** [comment]
Argh, the build is failing because as a fork PR, doesn't use the environment variables of the CI. Will fix tomorrow

**Comment by shiruba** [comment]
I added a few details, hope thats ok.

**Comment by lifenautjoe** [comment]
Thanks @shiruba !

**Pull request merged**
